// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnJAtcsIr2YPKZz3xaqZ-vRcTTtKWq6k',
    appId: '1:899277817497:web:8594955b62def84f115a08',
    messagingSenderId: '899277817497',
    projectId: 'conference-f4437',
    authDomain: 'conference-f4437.firebaseapp.com',
    storageBucket: 'conference-f4437.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAru98BdPFgrkooE3cfgAdR7bu7FLEXdqM',
    appId: '1:899277817497:android:ba9812499db8c9c0115a08',
    messagingSenderId: '899277817497',
    projectId: 'conference-f4437',
    storageBucket: 'conference-f4437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBFJjVO5j50SmDqhP0Q3LI6ixvynzMPhQ',
    appId: '1:899277817497:ios:252c00fb300990cb115a08',
    messagingSenderId: '899277817497',
    projectId: 'conference-f4437',
    storageBucket: 'conference-f4437.firebasestorage.app',
    iosBundleId: 'com.example.conference',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBFJjVO5j50SmDqhP0Q3LI6ixvynzMPhQ',
    appId: '1:899277817497:ios:252c00fb300990cb115a08',
    messagingSenderId: '899277817497',
    projectId: 'conference-f4437',
    storageBucket: 'conference-f4437.firebasestorage.app',
    iosBundleId: 'com.example.conference',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwnJAtcsIr2YPKZz3xaqZ-vRcTTtKWq6k',
    appId: '1:899277817497:web:5e222d560b532c40115a08',
    messagingSenderId: '899277817497',
    projectId: 'conference-f4437',
    authDomain: 'conference-f4437.firebaseapp.com',
    storageBucket: 'conference-f4437.firebasestorage.app',
  );
}
